owner: NoPlagiarism
repo: services-personal-upptime

user-agent: "@NoPlagiarism / services-personal-upptime"

sites:
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  theme: dark
  name: Services upptime
  baseUrl: "/services-personal-upptime"
  introTitle: "Services (usually frontend-alternatives) upptime"
  introMessage: "Check links above. They're cool :D"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Frontend instances lists
      href: https://github.com/NoPlagiarism/frontend-instances-list
    - title: Alternative Frontends
      href: https://github.com/digitalblossom/alternative-frontends
