name: Update Instances

on:
  schedule:
    - cron: '00 15 */3 * *'
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies for update_instances.py
      run: |
        python -m pip install --upgrade pip
        pip install -r custom/requirements_ui.py.txt
    - name: Updating instances
      run: python custom/update_instances.py
    - name: Install dependencies for clear_issues.py
      run: |
        pip install -r custom/requirements_ci.py.txt
    - name: Clearing issues
      env:
        GH_PAT: ${{ secrets.GH_PAT || github.token }}
      run: python custom/close_issues.py
    - name: Commit changes
      id: commit
      uses: EndBug/add-and-commit@v9
      with:
        add: '.upptimerc.yml'
        message: 'Update Instances'
        default_author: github_actions
        push: true
    - name: Activate setup if commit made
      if: steps.commit.outputs.committed == 'true'
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Setup CI
        token: ${{ secrets.GH_PAT }}
